@startuml casosusocoffeshop

class Usuario {
    - id: int
    - nombre: String
    - correo: String
    + iniciarSesion(): boolean
}

class Estudiante {
    + realizarPedido(menu: Menu, items: list<item>, metodoPago: String): Pedido
     
}

class Administrador {}
@enduml